// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleRentalMarketplace.Data;

#nullable disable

namespace VehicleRentalMarketplace.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818080619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ApproveBy")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ListingTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RenterID")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AssetID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ListingTypeID");

                    b.HasIndex("RenterID");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetID = 1,
                            ApprovalStatus = "Approved",
                            ApproveBy = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyRate = 45.00m,
                            Description = "Well-maintained sedan with leather seats, navigation, and backup camera. Perfect for business trips or family outings.",
                            IsActive = true,
                            ListingTypeID = 1,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            Status = "Available",
                            Title = "2024 Toyota Camry"
                        },
                        new
                        {
                            AssetID = 2,
                            ApprovalStatus = "Approved",
                            ApproveBy = 1,
                            CategoryID = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Powerful pickup truck with towing package, 4x4 capability, and bed liner. Great for construction or outdoor work.",
                            IsActive = true,
                            ListingTypeID = 2,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            SalePrice = 35000.00m,
                            Status = "Available",
                            Title = "2019 Ford F-150"
                        },
                        new
                        {
                            AssetID = 3,
                            ApprovalStatus = "Approved",
                            ApproveBy = 1,
                            CategoryID = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyRate = 85.00m,
                            Description = "Electric vehicle with autopilot, panoramic roof, and premium sound system. Zero emissions, instant torque.",
                            IsActive = true,
                            ListingTypeID = 3,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            SalePrice = 48000.00m,
                            Status = "Rented",
                            Title = "2023 Tesla Model 3"
                        },
                        new
                        {
                            AssetID = 4,
                            ApprovalStatus = "Pending",
                            CategoryID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyRate = 75.00m,
                            Description = "Off-road capable SUV with removable doors and roof. Perfect for adventure seekers.",
                            IsActive = true,
                            ListingTypeID = 1,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            Status = "Available",
                            Title = "2022 Jeep Wrangler"
                        },
                        new
                        {
                            AssetID = 5,
                            ApprovalStatus = "Approved",
                            ApproveBy = 1,
                            CategoryID = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mid-engine sports car with 490 horsepower, premium audio, and performance exhaust.",
                            IsActive = true,
                            ListingTypeID = 2,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            SalePrice = 68000.00m,
                            Status = "Available",
                            Title = "2021 Chevrolet Corvette"
                        },
                        new
                        {
                            AssetID = 6,
                            ApprovalStatus = "Approved",
                            ApproveBy = 1,
                            CategoryID = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyRate = 55.00m,
                            Description = "Compact SUV with hybrid engine, spacious cargo area, and Honda Sensing safety features.",
                            IsActive = true,
                            ListingTypeID = 3,
                            Location = "Los Angeles, CA",
                            RenterID = 3,
                            SalePrice = 32000.00m,
                            Status = "Sold",
                            Title = "2024 Honda CR-V"
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ListingTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.HasIndex("ListingTypeID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Sedan",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standard 4-door passenger cars",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "SUV",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sport Utility Vehicles - spacious and versatile",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Luxury",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium luxury vehicles for rent",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Motorcycle",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two-wheeled motor vehicles for rent",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Van",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vans for passenger or cargo transport",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Electric",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric vehicles (EVs) for rent",
                            IsActive = true,
                            ListingTypeID = 1
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Truck",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pickup trucks for hauling and heavy duty",
                            IsActive = true,
                            ListingTypeID = 2
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Classic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic and vintage cars for sale",
                            IsActive = true,
                            ListingTypeID = 2
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Sports Car",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance sports cars",
                            IsActive = true,
                            ListingTypeID = 2
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Luxury",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium luxury vehicles for rent or purchase",
                            IsActive = true,
                            ListingTypeID = 3
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Electric",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric vehicles (EVs) for rent or purchase",
                            IsActive = true,
                            ListingTypeID = 3
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Convertible",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Convertible/Open top vehicles",
                            IsActive = true,
                            ListingTypeID = 3
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "SUV",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SUVs available for both rent and purchase",
                            IsActive = true,
                            ListingTypeID = 3
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.ListingType", b =>
                {
                    b.Property<int>("ListingTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingTypeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ListingTypeID");

                    b.ToTable("ListingTypes");

                    b.HasData(
                        new
                        {
                            ListingTypeID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicles available for rent only",
                            IsActive = true,
                            TypeName = "Rent"
                        },
                        new
                        {
                            ListingTypeID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicles available for purchase only",
                            IsActive = true,
                            TypeName = "Sale"
                        },
                        new
                        {
                            ListingTypeID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vehicles available for both rent and purchase",
                            IsActive = true,
                            TypeName = "Both"
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PurchasedID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID");

                    b.HasIndex("PurchasedID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            BookingID = 3,
                            PaidAt = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Credit Card",
                            PurchasedID = 1,
                            Status = "Completed",
                            TransactionNumber = "TXN-2026-001"
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Purchase", b =>
                {
                    b.Property<int>("PurchasedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchasedID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PurchasedID");

                    b.HasIndex("BookingID");

                    b.HasIndex("UserID");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchasedID = 1,
                            BookingID = 3,
                            Date = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 48000.00m,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Review", b =>
                {
                    b.Property<int>("ReviewerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewerID"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int?>("PurchasedID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewerID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("PurchasedID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewerID = 1,
                            Comment = "Excellent car! Very clean and well-maintained. Will rent again.",
                            CreatedAt = new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentID = 1,
                            Rating = 5,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full system access",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Regular user - can view assets",
                            IsActive = true,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can list and manage assets",
                            IsActive = true,
                            RoleName = "Seller"
                        },
                        new
                        {
                            RoleID = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can approve and moderate content",
                            IsActive = true,
                            RoleName = "Moderator"
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@vehiclemarketplace.com",
                            Firstname = "System",
                            IsActive = true,
                            Lastname = "Administrator",
                            PasswordHash = "QWRtaW4xMjMh",
                            RoleID = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Firstname = "John",
                            IsActive = true,
                            Lastname = "User",
                            PasswordHash = "VXNlcjEyMyE=",
                            PhoneNumber = "123-456-7890",
                            RoleID = 2,
                            Username = "john_user"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "123 Main St",
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@seller.com",
                            Firstname = "Jane",
                            IsActive = true,
                            Lastname = "Seller",
                            PasswordHash = "U2VsbGVyMTIzIQ==",
                            PhoneNumber = "987-654-3210",
                            RoleID = 3,
                            State = "CA",
                            Username = "jane_seller"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mod@moderator.com",
                            Firstname = "Mod",
                            IsActive = true,
                            Lastname = "Moderator",
                            PasswordHash = "TW9kMTIzIQ==",
                            PhoneNumber = "555-555-5555",
                            RoleID = 4,
                            Username = "moderator"
                        });
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Asset", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryID");

                    b.HasOne("VehicleRentalMarketplace.Models.ListingType", "ListingType")
                        .WithMany("Assets")
                        .HasForeignKey("ListingTypeID");

                    b.HasOne("VehicleRentalMarketplace.Models.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("RenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ListingType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Category", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.ListingType", "ListingType")
                        .WithMany("Categories")
                        .HasForeignKey("ListingTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListingType");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Payment", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.Asset", "Asset")
                        .WithMany("Payments")
                        .HasForeignKey("BookingID");

                    b.HasOne("VehicleRentalMarketplace.Models.Purchase", "Purchase")
                        .WithMany("Payments")
                        .HasForeignKey("PurchasedID");

                    b.Navigation("Asset");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Purchase", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.Asset", "Asset")
                        .WithMany("Purchases")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalMarketplace.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserID");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Review", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.Payment", "Payment")
                        .WithMany("Reviews")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRentalMarketplace.Models.Purchase", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PurchasedID");

                    b.HasOne("VehicleRentalMarketplace.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.User", b =>
                {
                    b.HasOne("VehicleRentalMarketplace.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Asset", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Category", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.ListingType", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Payment", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Purchase", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VehicleRentalMarketplace.Models.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
